### ISSUE TITLE
Compatibility with ntl-8.*

### ISSUE THREAD

**Issue by tom111** [Singular/Sources#710]
Hi,

ntl-8.* releases are appearing and Singular is currently not compatible. Something in the conversion interface changed:

    NTLconvert.cc: In function ‘CanonicalForm convertZZ2CF(const NTL::ZZ&)’:
    NTLconvert.cc:504:33: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
     long sizeofrep= ((long *) a.rep) [1];
                                 ^
    NTLconvert.cc:522:79: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
     int cc= mpn_get_str (cf_stringtemp, 16, (mp_limb_t *) (((long *) (a.rep)) + 2), sizeofrep);

**Comment by malex984** [comment]
Hi,

i thought that i have fixed this issue  with de688442dfe449992dc14a000bca06
91ecc7e106...

Could you please try building Singular with NTL 8 using the current
spielwiese HEAD checkout?

O.

Am Donnerstag, 26. März 2015 schrieb Thomas Kahle :

> Hi,
>
> ntl-8.* releases are appearing and Singular is currently not compatible.
> Something in the conversion interface changed:
>
> NTLconvert.cc: In function ‘CanonicalForm convertZZ2CF(const NTL::ZZ&)’:
> NTLconvert.cc:504:33: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
>  long sizeofrep= ((long *) a.rep) [1];
>                              ^
> NTLconvert.cc:522:79: error: invalid cast from type ‘const NTL::WrappedPtr<void, NTL::ZZ::Deleter>’ to type ‘long int*’
>  int cc= mpn_get_str (cf_stringtemp, 16, (mp_limb_t *) (((long *) (a.rep)) + 2), sizeofrep);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Singular/Sources/issues/710>.
>


-- 
Sincerely Yours,
---------------------------------------------------------------------
Dr. Oleksandr Motsak                Office 48 / R. 437
Fachbereich Mathematik        Tel.   +49-631-205-2738
TU Kaiserslautern             Fax    +49-631-205-4795
D-67653 Kaiserslautern        http://www.mathematik.uni-kl.de/~motsak
---------------------------------------------------------------------

**Comment by tom111** [comment]
Oh, I was testing the release version and did not check current HEAD. The patch works and is shipped in Gentoo's Singular package now. Thanks!
