### ISSUE TITLE
Debian: FTBFS with GCC 6: no matching function for call to (#811855)

### ISSUE THREAD

**Issue by jgmbenoit** [Singular/Sources#750]
A Debian bugreport has been filed to notice that Singular fails to build with GCC 6:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811855

Please note that it is expected that GCC 6 will become the default compiler for Stretch, the coming Debian stable distribution scheduled to be frozen at the end of the year 2016.

**Comment by hannes14** [comment]
Thanks for the report:
it is fixed now (see 6828dc2a9db4f0616aef09df69cf620b2f3ace02)

**Comment by jgmbenoit** [comment]
Perfect ! Thanks for your prompt reaction.
