### ISSUE TITLE
GCC 6 (6.1.1): segfault

### ISSUE THREAD

**Issue by jgmbenoit** [Singular/Sources#772]
Building the vanilla source with the GNU compiler 6 (6.1.1) introduced a segfault:
see [Debian bugreport 831072](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831072) for details

**Comment by hannes14** [comment]
quick fix: http://www.singular.uni-kl.de:8002/trac/changeset/b44baa157fd18423b13500e965be8a22fca8e651/git

see http://www.singular.uni-kl.de:8002/trac/ticket/769

**Comment by jgmbenoit** [comment]
Thanks for your prompt reply. The quick fix works.
