### ISSUE TITLE
potential rename of .pc file (and library)?

### ISSUE THREAD

**Issue by tom111** [Singular/Sources#783]
Hi Singular team,
I'm relaying this Gentoo bug https://bugs.gentoo.org/show_bug.cgi?id=591556
It occurred to us that (at least) the file "resources.pc" has a quite generic name. Another packge (paint-mono) wants to install the same file. Would it be possible to rename your library and .pc file to something more specific, like "singular-resources". That would make it easier for distributions.
Thanks,
Thomas

**Comment by hannes14** [comment]
library, include file and pkgconfig file renamed (resources -> singular_resources),
see a3a6a07858b7e91c4c8a3c8d07e53957a8547af2

**Comment by tom111** [comment]
Great! Thanks.
