### ISSUE TITLE
version 4.1.1: syzextra test fails on Debian build

### ISSUE THREAD

**Issue by jgmbenoit** [Singular/Sources#858]
I am currently packaging version 4.1.1 for Debian on behalf of the Debian Science Team. Every thing is fine except  that the test for syzextra fails: please find in attachment the log file.
[syzextra-test_release.sh.log](https://github.com/Singular/Sources/files/1754598/syzextra-test_release.sh.log)
Any idea ?

**Comment by jgmbenoit** [comment]
I have just tried to build Singular 4.1.1 from the [source ball](http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/4-1-1/singular-4.1.1.tar.gz) in a Debian Sid environment: the syzextra test fails as well.
For comparison, I try the same with version 4.1.0-p3 in the same environment: I can build and check it.
Please let me know if you can reproduce it, if you need more details.

**Comment by hannes14** [comment]
see https://www.singular.uni-kl.de/index.php/singular-report-bugs.html
syzextra is depreciated in 4.1.1, not in the documentation any more and only used in one library(deRham.lib). Will be substituted by fres soon.
http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/4-1-1/singular-4.1.1p1.tar.gz
fixes the syzextra test

**Comment by jgmbenoit** [comment]
Thanks for the clarification. I have just build the source tarball  in the condition, and it rocks as announced.
So I am closing.
