### ISSUE TITLE
coeffs_test test fails on arm*, mips*, and s390x architectures within Debian Sid

### ISSUE THREAD

**Issue by jgmbenoit** [Singular/Sources#862]
the logs are available [here](https://buildd.debian.org/status/package.php?p=singular&suite=experimental).
Let me know if any help is needed.

**Comment by hannes14** [comment]
Please reports bugs/issues at https://www.singular.uni-kl.de/index.php/singular-report-bugs.html

Issue should be fixed with 2a4a23dde834fbffe65259963c9f76b660ff0b19,
(ftp://www.mathematik.uni-kl.de/pub/Math/Singular/src/4-1-1/singular-4.1.1p2.tar.gz)

**Comment by jgmbenoit** [comment]
The issue appeared to fixed. Thanks.
